In [2]:
import pandas as pd
import numpy as np

In [12]:
results_df = pd.read_excel('../nfl_game_results.xlsx')

In [13]:
results_df.head()

,Week,Day,Date,Time,Winner/tie,Unnamed: 5,Loser/tie,PtsW,PtsL,YdsW,TOW,YdsL,TOL,Season,Home Team,Away Team
0,1,Thu,2019-09-07,8:37PM,Pittsburgh Steelers,NaN,Miami Dolphins,28,17,342,1,278,2,2006,Pittsburgh Steelers,Miami Dolphins
1,1,Sun,2019-09-10,1:00PM,Cincinnati Bengals,@,Kansas City Chiefs,23,10,236,1,289,3,2006,Kansas City Chiefs,Cincinnati Bengals
2,1,Sun,2019-09-10,1:01PM,Baltimore Ravens,@,Tampa Bay Buccaneers,27,0,271,0,142,3,2006,Tampa Bay Buccaneers,Baltimore Ravens
3,1,Sun,2019-09-10,1:02PM,New England Patriots,NaN,Buffalo Bills,19,17,319,2,240,0,2006,New England Patriots,Buffalo Bills
4,1,Sun,2019-09-10,1:02PM,Philadelphia Eagles,@,Houston Texans,24,10,441,1,241,0,2006,Houston Texans,Philadelphia Eagles